name: Go Build
on:
  push:
    branches:
      - main
      - workflows

# The API requires write permission on the repository to submit dependencies
permissions:
  contents: write

# Environment variables to configure Go and Go modules. Customize as necessary
env:
  GOPROXY: '' # A Go Proxy server to be used
  GOPRIVATE: '' # A list of modules are considered private and not requested from GOPROXY

jobs:
  go-build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Go Dependency Submission
        uses: actions/go-dependency-submission@v1.0.2

      - name: Set up Go
        uses: actions/setup-go@v3.5.0
        with:
          go-version: 'stable'
          cache: true
          cache-dependency-path: go.sum
          check-latest: true
          architecture: amd64
      - run: go build -o gitlab-job-file-downloader
  upload-artifact:
    name: Upload Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Accidentally upload to the same artifact via multiple jobs
        uses: actions/upload-artifact@v3
        with:
            name: sh-artifact
            path: ${{ github.workspace }}/gitlab-job-file-downloader
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'go' ]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
